version: "3"

services:
  nginx:
    container_name: cm_nginx
    image: nginx:1.23.1-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/collectstatic:/static
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - cm_web

  cm_web:
    container_name: cm_web
    image: coolmarks
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./data:/src/data
