version: "3"

services:
  nginx:
    container_name: coolmarks-nginx
    image: nginx:alpine-slim
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/collectstatic:/static
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - coolmarks-backend

  coolmarks-backend:
    container_name: coolmarks-backend
    image: coolmarks-backend
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./data:/src/data
